# Generated by Django 4.2.11 on 2024-07-23 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, max_length=255, null=True, verbose_name='مهارت\u200cها')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='تجربیات')),
                ('career_goals', models.TextField(blank=True, null=True, verbose_name='اهداف حرفه\u200cای')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CV.education', verbose_name='تحصیلات')),
                ('languages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CV.languages', verbose_name='زبان ها')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='professional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'آقا'), ('female', 'خانم')], max_length=10, verbose_name='جنسیت')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='خلاصه حرفه\u200cای')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='تلفن همراه')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='تلفن ثابت')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='لینک لینکدین')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='تصویر')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('job_title', models.CharField(max_length=255, verbose_name='عنوان شغلی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_current_job', models.BooleanField(default=False, verbose_name='شغل فعلی')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='مسئولیت\u200cها و وظایف')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='دستاوردها و موفقیت\u200cها')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='محل کار')),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'تمام وقت'), ('part_time', 'پاره\u200cوقت'), ('contract', 'قراردادی'), ('internship', 'کارآموزی'), ('telecommuting', 'دورکاری')], max_length=50, null=True, verbose_name='نوع استخدام')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
