# Generated by Django 4.2.11 on 2024-07-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalsummary',
            name='languages',
        ),
        migrations.AddField(
            model_name='professionalsummary',
            name='languages',
            field=models.ManyToManyField(blank=True, to='CV.languages'),
        ),
    ]
