# Generated by Django 4.2.11 on 2024-07-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_remove_professionalsummary_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalsummary',
            name='languages',
        ),
        migrations.AddField(
            model_name='professionalsummary',
            name='languages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CV.languages', verbose_name='زبان ها'),
        ),
    ]
