# Generated by Django 4.2.11 on 2024-07-23 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0003_remove_professionalsummary_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='instagram_url',
        ),
    ]
