# Generated by Django 5.1 on 2024-10-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0004_remove_person_instagram_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(null=True, upload_to='%Y-%m-%d', verbose_name='تصویر'),
        ),
    ]
