# Generated by Django 5.1 on 2024-10-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0005_alter_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', 'Bachelor Degree'), ('master', 'Master Degree'), ('doctorate', 'Doctorate Degree')], max_length=20),
        ),
    ]
