# Generated by Django 5.1 on 2024-10-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0006_education_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
