# Generated by Django 5.1 on 2024-10-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0007_person_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
        migrations.AddField(
            model_name='person',
            name='person_image',
            field=models.ImageField(null=True, upload_to='%Y-%m-%d', verbose_name='تصویر پروفایل'),
        ),
        migrations.AddField(
            model_name='professionalsummary',
            name='summary_image',
            field=models.ImageField(null=True, upload_to='%Y-%m-%d', verbose_name='تصویر رزومه'),
        ),
    ]
