# Generated by Django 5.1 on 2024-10-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0008_remove_person_image_person_person_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
