# Generated by Django 5.1 on 2024-10-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0009_jobhistory_company_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
