# Generated by Django 5.1 on 2024-10-13 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0012_alter_education_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalsummary',
            name='career_goals',
            field=models.TextField(null=True, verbose_name='اهداف حرفه\u200cای'),
        ),
        migrations.AlterField(
            model_name='professionalsummary',
            name='experience',
            field=models.TextField(null=True, verbose_name='تجربیات'),
        ),
        migrations.AlterField(
            model_name='professionalsummary',
            name='languages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CV.languages', verbose_name='زبان ها'),
        ),
        migrations.AlterField(
            model_name='professionalsummary',
            name='summary_image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y-%m-%d', verbose_name='تصویر رزومه'),
        ),
    ]
