# Generated by Django 5.1 on 2024-10-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0016_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
