# Generated by Django 5.1 on 2024-10-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0020_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
